/*
 *  This file is part of ConPianist. See <https://github.com/hugbug/conpianist>.
 *
 *  Copyright (C) 2018 Andrey Prygunkov <hugbug@users.sourceforge.net>
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation; either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

#include "Presets.h"

namespace
{
	using U = CharPointer_UTF8;

	Voice voicesArr[721] {
		{"PRESET:/VOICE/Piano/Grand Piano/CFX Grand.T542.VRM", "VRM", "Piano", "Grand Piano"},
		{U("PRESET:/VOICE/Piano/Grand Piano/Bösendorfer.T543.VRM"), "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Pop Grand.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Mellow Piano.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Studio Grand.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Themic Grand.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Bright Piano.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Ambient Piano.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Rock Piano.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Stage Piano.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Grand Piano 1octave.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Grand Piano 2octaves.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Grand Piano/Cocktail Piano.T228.VRM", "VRM", "Piano", "Grand Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/Upright Piano.T544.VRM", "VRM", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/Pop Upright.T229.NLV", "Natural!", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/70s Ballad Piano.T229.NLV", "Natural!", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/Chill Out Piano.T229.NLV", "Natural!", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/Honky Tonk Upright.T229.NLV", "Natural!", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/Saloon Upright.T229.NLV", "Natural!", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/Upright 1octave.T229.NLV", "Natural!", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Upright Piano/Upright 2octaves.T229.NLV", "Natural!", "Piano", "Upright Piano"},
		{"PRESET:/VOICE/Piano/Piano Layer/Superstar Grand.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/Imperial Ballad.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/MIDI Grand.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/MIDI Grand Pad.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/Bright Grand Pad.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/Grand Pad Layer.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/Piano & EP.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/Grand Piano & Strings.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Piano Layer/Grand Piano & Orchestra.T230.NLV", "Natural!", "Piano", "Piano Layer"},
		{"PRESET:/VOICE/Piano/Electric Piano/Suitcase EP.T327.CLV", "Cool!", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Vintage EP.T327.VCE", "Regular", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Electric Piano 1.T327.CLV", "Cool!", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Electric Piano 2.T327.NLV", "Natural!", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Stage EP.T327.VCE", "Regular", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Funky EP.T327.NLV", "Natural!", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Tremolo Suitcase EP.T327.CLV", "Cool!", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Tremolo Stage EP.T327.NLV", "Natural!", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Smooth Tine.T327.VCE", "Regular", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/CP80 Stage.T231.VCE", "Regular", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/Electric Piano/Magnetics.T327.VCE", "Regular", "Piano", "Electric Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Studio Ballad DX.T232.VCE", "Regular", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Sparkle Stack.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Sweet DX.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Ballad DX.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/DX Dynamics.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Ballad Bells.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Galaxy EP.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/DX7 EP.T232.NLV", "Natural!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Dream DX.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Midnight DX.T232.CLV", "Cool!", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Piano Sweeper.T232.VCE", "Regular", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/FM E.Piano/Pianosphere.T232.VCE", "Regular", "Piano", "FM E.Piano"},
		{"PRESET:/VOICE/Piano/Clavi/Clavi Bright.T233.VCE", "Regular", "Piano", "Clavi"},
		{"PRESET:/VOICE/Piano/Clavi/Wah Clavi.T233.VCE", "Regular", "Piano", "Clavi"},
		{"PRESET:/VOICE/Piano/Clavi/Phase Clavi.T233.VCE", "Regular", "Piano", "Clavi"},
		{"PRESET:/VOICE/Piano/Harpsichord/Harpsichord 1.T234.NLV", "Natural!", "Piano", "Harpsichord"},
		{"PRESET:/VOICE/Piano/Harpsichord/Harpsichord 2.T234.SAR", "S.Art!", "Piano", "Harpsichord"},
		{"PRESET:/VOICE/Piano/Harpsichord/Harpsichord Coupler.T234.NLV", "Natural!", "Piano", "Harpsichord"},
		{"PRESET:/VOICE/Piano/Harpsichord/Grand Harpsichord.T234.LIV", "Live!", "Piano", "Harpsichord"},
		{"PRESET:/VOICE/Piano/Harpsichord/Harpsichord & Strings.T234.NLV", "Natural!", "Piano", "Harpsichord"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Whiter Bars.T235.SAR", "S.Art!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Curved Bars.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/All Bars Out.T235.SAR", "S.Art!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Even Bars.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Jazz Rotary.T235.SAR", "S.Art!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Vintage Fast.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Classic Bars.T235.SAR", "S.Art!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Scanner Jazz.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Rock Rotary.T235.SAR", "S.Art!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Organ-a-Go-Go.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Prog Rock Organ.T235.SAR", "S.Art!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/R&B Tremolo.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Classic Jazz.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Hold It Fast.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Full Rocker.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Organ Accomp 1.T235.VCE", "Regular", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Organ Accomp 2.T235.VCE", "Regular", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Organ Accomp 3.T235.VCE", "Regular", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Organ Accomp 4.T235.VCE", "Regular", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Organ Accomp 5.T235.VCE", "Regular", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Whiter Bars Slow.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Whiter Bars Fast.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Jazz Organ Slow.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Jazz Organ Fast.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/All Bars Out Slow.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/All Bars Out Fast.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/All Bars Phase.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Rotor Organ.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Mellow Drawbar.T235.VCE", "Regular", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Tonewheel Organ/Two Channels Organ.T235.CLV", "Cool!", "Organ", "Tonewheel Organ"},
		{"PRESET:/VOICE/Organ/Transistor Organ/60s Combo 1.T236.CLV", "Cool!", "Organ", "Transistor Organ"},
		{"PRESET:/VOICE/Organ/Transistor Organ/60s Combo 2.T236.CLV", "Cool!", "Organ", "Transistor Organ"},
		{"PRESET:/VOICE/Organ/Transistor Organ/60s Combo 3.T236.CLV", "Cool!", "Organ", "Transistor Organ"},
		{"PRESET:/VOICE/Organ/Transistor Organ/60s Combo 4.T236.CLV", "Cool!", "Organ", "Transistor Organ"},
		{"PRESET:/VOICE/Organ/Transistor Organ/Euro Organ.T236.VCE", "Regular", "Organ", "Transistor Organ"},
		{"PRESET:/VOICE/Organ/Classical Pipe/Pipe Organ Principal.T237.NLV", "Natural!", "Organ", "Classical Pipe"},
		{"PRESET:/VOICE/Organ/Classical Pipe/Chapel Organ.T237.VCE", "Regular", "Organ", "Classical Pipe"},
		{"PRESET:/VOICE/Organ/Classical Pipe/Full Organ.T237.VCE", "Regular", "Organ", "Classical Pipe"},
		{"PRESET:/VOICE/Organ/Classical Pipe/Hymn Organ.T237.VCE", "Regular", "Organ", "Classical Pipe"},
		{"PRESET:/VOICE/Organ/Classical Pipe/Pipe Organ Tutti.T237.NLV", "Natural!", "Organ", "Classical Pipe"},
		{"PRESET:/VOICE/Organ/Classical Pipe/Church Organ.T237.VCE", "Regular", "Organ", "Classical Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Full Theatre.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Sweet Theatre.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Ballroom Organ.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Tibia 8'.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Tibia 8'&4'.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Tibia 16'&4'.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Tibia Chorus.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Vox Humana 8'.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Vox Humana & Tibia.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Theatre Kinura 8'.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Theatre Trumpet 8'.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Theatre Trumpet & Kinura.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Theatre Pipe/Theatre Trumpet 16'&8'.T238.VCE", "Regular", "Organ", "Theatre Pipe"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Organ Flutes.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/USD Smile.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Reggae Bars.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Warm Theatre.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Organ Pops.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Rock Organ.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Soul Percussion.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Gospel Truth.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Pad Organ.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Full Organ.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/String Bars.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Latin Spin.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Shady Bars.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Funk Organ.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Ballad Organ.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Rich Bars.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Trumpet Bars.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Soul Bars.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Clari Bars.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Jazz Squabble.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Euro Perc.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Ballad Euro.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Euro Reeds.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Even Warmth.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Bright Euro.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Full Euro.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Euro Pops.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Euro Accomp 1.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Euro Accomp 2.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Organ Flutes/Euro Accomp 3.T239.ORG", "OrganFlutes", "Organ", "Organ Flutes"},
		{"PRESET:/VOICE/Organ/Harmonica/Harmonica.T240.SWV", "Sweet!", "Organ", "Harmonica"},
		{"PRESET:/VOICE/Organ/Harmonica/Modern Harp.T240.VCE", "Regular", "Organ", "Harmonica"},
		{"PRESET:/VOICE/Organ/Harmonica/Blues Harp.T240.VCE", "Regular", "Organ", "Harmonica"},
		{"PRESET:/VOICE/Organ/Accordion/Full Accordion Register.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/French Musette Acc..T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Master Accordion.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Steirische.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Jazz Accordion.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Cassotto.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Cajun.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Accordion Clarinet.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Bandoneon.T328.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Tango Accordion.T328.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Full Register Bass.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Musette Bass.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Master Bass.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Cajun Bass.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Accordion Bass.T241.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Organ/Accordion/Tango Bass.T328.VCE", "Regular", "Organ", "Accordion"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Concert Guitar.T242.SAR", "S.Art!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Dynamic Nylon.T242.LIV", "Live!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Flamenco Guitar.T330.SAR", "S.Art!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Hard Flamenco.T330.LIV", "Live!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Nylon Guitar.T242.SAR", "S.Art!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Classical Guitar.T242.LIV", "Live!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Slide Nylon.T242.LIV", "Live!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Nylon Mute.T242.LIV", "Live!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Nylon Acoustic/Electro Acoustic Guitar.T242.SAR", "S.Art!", "Guitar & Bass", "Nylon Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Steel Acoustic/Steel Guitar.T243.SAR", "S.Art!", "Guitar & Bass", "Steel Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Steel Acoustic/Slide Steel.T243.LIV", "Live!", "Guitar & Bass", "Steel Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Steel Acoustic/Folk Guitar Harmonics.T243.SAR", "S.Art!", "Guitar & Bass", "Steel Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Steel Acoustic/Dynamic Steel.T243.LIV", "Live!", "Guitar & Bass", "Steel Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Steel Acoustic/Steel Guitar Strum.T243.LIV", "Live!", "Guitar & Bass", "Steel Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Steel Acoustic/Steel Guitar Mute.T243.LIV", "Live!", "Guitar & Bass", "Steel Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Steel Acoustic/12String Guitar.T243.LIV", "Live!", "Guitar & Bass", "Steel Acoustic"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Bright Chorus.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Vintage Slap.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Ballad Delay.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Vintage Pure.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Finger Bright.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Cool Wah Guitar.T244.VCE", "Regular", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Semi Acoustic.T332.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Jazz Vintage.T332.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Jazz Artist.T332.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Smooth Jazz Guitar.T332.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Shadowed Guitar.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Finger Chorus.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Vintage Spring.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Light Chorus.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Country Pick.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Finger Slap Slide.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Warm Solid.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Warm Electric.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Clean Solid.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Clean Electric.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Slap Solid.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Lounge Guitar.T332.VCE", "Regular", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Funk Slap.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Single Coil Clean.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/70s Solid Guitar.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Pure Vintage.T244.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Vintage Open.T244.VCE", "Regular", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Chorus Solid.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Clean Guitar.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Jazz Clean.T332.SAR", "S.Art!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Slide Clean.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Muted Guitar.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Slide Solid.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Dynamic Mute.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Slide Pick.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Vintage Muted Guitar.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Slide Finger.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Vintage Muted Echo.T244.VCE", "Regular", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Slide Warm.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Slide Jazz.T332.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Funk Guitar.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Vintage Strum.T244.VCE", "Regular", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Tremolo Solid.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Ballad Solid.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Jazz Guitar.T332.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Jazz Solo Guitar.T332.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Octave Guitar.T332.VCE", "Regular", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/Electric Guitar.T244.CLV", "Cool!", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Clean Solid/60s Clean.T244.VCE", "Regular", "Guitar & Bass", "Clean Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Rock Hero.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Overdrive Wah.T333.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Vintage Rock.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Vintage Blues.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Stage Lead.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Blues Slap Slide.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Heavy Rock.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Blues Bright.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Classic Stack.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Blues Warm.T333.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Guitar Hero.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Vintage Amp.T244.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Feedbacker.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Finger Amp.T244.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Rock Legend.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Slide Pick Amp.T244.CLV", "Cool!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Crunch Guitar.T245.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Bluesy Night.T333.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Stereo Rock.T245.CLV", "Cool!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Half Drive.T333.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Blues Guitar.T245.CLV", "Cool!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Grunge Guitar.T333.SAR", "S.Art!", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/Distortion Solid/Metal Master.T245.VCE", "Regular", "Guitar & Bass", "Distortion Solid"},
		{"PRESET:/VOICE/Guitar & Bass/World/Pedal Steel Amp.T329.SAR", "S.Art!", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Mandolin.T331.SWV", "Sweet!", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Pedal Steel.T329.SAR", "S.Art!", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Banjo.T378.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Zither 1.T325.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Zither 2.T325.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Shamisen.T381.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Dulcimer.T366.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Koto.T380.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Hackbrett.T366.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Aloha Guitar.T329.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Sitar.T379.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/World/Pedal Steel.T329.VCE", "Regular", "Guitar & Bass", "World"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Round Bass.T247.SAR", "S.Art!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Acoustic Bass.T337.SAR", "S.Art!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Flatwound Bass.T247.SAR", "S.Art!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Soft Acoustic Bass.T337.SAR", "S.Art!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Mute Bass.T247.SAR", "S.Art!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Fretless Bass.T334.SAR", "S.Art!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Soft Acoustic Bass.T337.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Acoustic Bass.T337.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Ballroom Bass.T337.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Round Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Flatwound Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Acoustic Bass & Cymbal.T337.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Mute Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Fusion Bass.T247.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Pick Bass.T247.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Dyno Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Fretless Bass.T334.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Slap Bass.T247.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Rock Bass.T247.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Mellow Finger Bass.T247.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Pick Bass.T247.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Pick Dyno Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Electric Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Half Mute Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Super Fretless Bass.T334.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Vintage Pick Mute Bass.T247.CLV", "Cool!", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Bass/Funk Bass.T247.VCE", "Regular", "Guitar & Bass", "Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Lo Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Fat Pulse.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Dark Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Wazzo Saw.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Moon Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Deep Point.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Kick Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Tight Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Club Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Competitor.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/1o1 Sub.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Trance Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Little Bass Synth.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Sub Cut Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Tekno Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Dyno Acid Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Perc Punch.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Mini Sub.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Square Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Fat Sine Resonance.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Ballad Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/House Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Velo Master.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Big Drone.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Sub Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Hard Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/Resonance Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Guitar & Bass/Synth Bass/TB Bass.T248.VCE", "Regular", "Guitar & Bass", "Synth Bass"},
		{"PRESET:/VOICE/Strings & Vocal/String Solo/Violin.T249.SWV", "Sweet!", "Strings & Vocal", "String Solo"},
		{"PRESET:/VOICE/Strings & Vocal/String Solo/Solo Violin.T249.VCE", "Regular", "Strings & Vocal", "String Solo"},
		{"PRESET:/VOICE/Strings & Vocal/String Solo/Viola.T335.VCE", "Regular", "Strings & Vocal", "String Solo"},
		{"PRESET:/VOICE/Strings & Vocal/String Solo/Fiddle.T249.VCE", "Regular", "Strings & Vocal", "String Solo"},
		{"PRESET:/VOICE/Strings & Vocal/String Solo/Cello.T336.VCE", "Regular", "Strings & Vocal", "String Solo"},
		{"PRESET:/VOICE/Strings & Vocal/String Solo/Contrabass.T337.VCE", "Regular", "Strings & Vocal", "String Solo"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Classical Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Concert Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Theatre Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Pizzicato.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Lush Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Tremolo Strings.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Ballroom Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Spiccato.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Studio Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Movie Strings.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Ballad Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Disco Strings 1.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Disco Strings 2.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Warm Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Tremolo Strings.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Big Strings.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Strings.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Strings f.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Allegro.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Strings mf.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Dynamic Strings.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Strings p.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Chamber Strings.T250.VCE", "Regular", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Tremolo Sforzando.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Tremolo Bowing.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Spiccato.T250.SAR", "S.Art!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Spiccato.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Strings f.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Strings f.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Strings mf.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Strings mf.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Real Strings p.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/String Ensemble/Strings p.T250.LIV", "Live!", "Strings & Vocal", "String Ensemble"},
		{"PRESET:/VOICE/Strings & Vocal/Orchestral Layers/Tutti.T251.VCE", "Regular", "Strings & Vocal", "Orchestral Layers"},
		{"PRESET:/VOICE/Strings & Vocal/Orchestral Layers/Theatre Orchestra.T251.VCE", "Regular", "Strings & Vocal", "Orchestral Layers"},
		{"PRESET:/VOICE/Strings & Vocal/Orchestral Layers/Symphonic Unison.T251.VCE", "Regular", "Strings & Vocal", "Orchestral Layers"},
		{"PRESET:/VOICE/Strings & Vocal/Orchestral Layers/Pizzicato Glocken.T251.LIV", "Live!", "Strings & Vocal", "Orchestral Layers"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Boys Choir Aah.T255.SAR", "S.Art!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Boys Choir Ooh.T255.SAR", "S.Art!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Boys Choir Aah.T255.LIV", "Live!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Boys Choir Ooh.T255.LIV", "Live!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Soft Choir Ooh.T255.SAR", "S.Art!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Soft Choir Aah.T255.SAR", "S.Art!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Boys Choir Oh-Ah (Pedal).T255.SAR", "S.Art!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Boys Choir Oh-Ah.T255.SAR", "S.Art!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Gothic Vox.T255.VCE", "Regular", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Gospel Voices.T254.LIV", "Live!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Humming.T254.LIV", "Live!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Hah Choir.T255.VCE", "Regular", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Strings & Vocal/Choir/Mmh.T252.LIV", "Live!", "Strings & Vocal", "Choir"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Bright Trumpet.T256.SAR", "S.Art!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Cornet.T256.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Silver Trumpet.T256.SAR", "S.Art!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Muted Trumpet.T340.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Golden Trumpet.T256.SAR", "S.Art!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Flugel Horn.T341.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Big Band Trumpet.T256.SAR", "S.Art!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Trombone.T342.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Trumpet Fall.T256.SAR", "S.Art!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Trumpet.T256.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Trumpet Shake.T256.SAR", "S.Art!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Mellow Trumpet.T256.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Silver Trumpet.T256.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Muted Cornet.T340.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Golden Trumpet.T256.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Baritone Horn.T344.VCE", "Regular", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Tuba.T344.VCE", "Regular", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Bright Trombone.T342.SWV", "Sweet!", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Baritone Hit.T344.VCE", "Regular", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Solo/Alp Bass.T344.VCE", "Regular", "Brass & Woodwind", "Brass Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Horns.T343.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Big Band Brass.T257.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Soft Horns.T343.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Smooth Brass.T257.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Dynamic Brass.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Symphony Horns 1.T343.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Symphony Horns 2.T343.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Power Brass.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Warm Horns.T343.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Accent Brass.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Stopped Horns.T343.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass Falls f.T257.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Muted Horns.T343.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass Falls mf.T257.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass f.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass Band.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass mf.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Soft Horns.T343.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass p.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Soft Trombones.T345.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass Shake.T257.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Pop Brass.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Accent Falls.T257.SAR", "S.Art!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Hyper Brass.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Sforzando.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Small Brass.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Sforzando Fall.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Ballroom Brass.T257.VCE", "Regular", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Brass Dynamics.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Brass Ensemble/Octave Brass.T257.LIV", "Live!", "Brass & Woodwind", "Brass Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Saxophone.T348.SAR", "S.Art!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Alto Sax.T258.SAR", "S.Art!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Big Band Sax.T348.SAR", "S.Art!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Soft Alto Sax.T258.SAR", "S.Art!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Rock Sax.T348.SAR", "S.Art!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Growl Sax.T348.SWV", "Sweet!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Soprano Sax.T347.SWV", "Sweet!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Pop Tenor Sax.T348.SWV", "Sweet!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Pop Alto Sax.T258.SWV", "Sweet!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Ballad Tenor Sax.T348.SWV", "Sweet!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Breathy Tenor Sax.T348.SWV", "Sweet!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Jazz Tenor Sax.T348.SWV", "Sweet!", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Solo/Baritone Sax.T349.VCE", "Regular", "Brass & Woodwind", "Sax Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Sax Section.T259.SAR", "S.Art!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Big Band Octave.T259.LIV", "Live!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Sax Section Unison.T259.SAR", "S.Art!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Big Band Unison.T259.LIV", "Live!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Sax Section Fast Attack.T259.LIV", "Live!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Big Band Saxes.T259.LIV", "Live!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Sax Section Octave.T259.SAR", "S.Art!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Ballad Section.T259.VCE", "Regular", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Soft Saxes.T259.SAR", "S.Art!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Sax Appeal.T259.LIV", "Live!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Sax Section Hard.T259.LIV", "Live!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Moonlight.T261.VCE", "Regular", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Sax Ensemble/Sax Section Soft.T259.LIV", "Live!", "Brass & Woodwind", "Sax Ensemble"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Orchestral Flute.T260.SAR", "S.Art!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Jazz Flute.T260.SWV", "Sweet!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Orchestral Oboe.T350.SAR", "S.Art!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Classical Oboe.T350.SWV", "Sweet!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Orchestral Clarinet.T346.LIV", "Live!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Jazz Clarinet.T346.SWV", "Sweet!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Orchestral Bassoon.T352.SWV", "Sweet!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Bassoon.T352.VCE", "Regular", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/German Clarinet.T346.VCE", "Regular", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Classical Flute.T260.SWV", "Sweet!", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Piccolo.T354.VCE", "Regular", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Oboe.T350.VCE", "Regular", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/Clarinet.T346.VCE", "Regular", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Solo/English Horn.T351.VCE", "Regular", "Brass & Woodwind", "Woodwind Solo"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Ens/Flutes & Oboes.T261.VCE", "Regular", "Brass & Woodwind", "Woodwind Ens"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Ens/Orchestral Woodwind.T261.VCE", "Regular", "Brass & Woodwind", "Woodwind Ens"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Ens/Clarinet & Flutes.T261.VCE", "Regular", "Brass & Woodwind", "Woodwind Ens"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Ens/Alto Flutes.T260.VCE", "Regular", "Brass & Woodwind", "Woodwind Ens"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Ens/Clarinet & Oboe.T261.VCE", "Regular", "Brass & Woodwind", "Woodwind Ens"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Ens/Flute Ensemble.T261.VCE", "Regular", "Brass & Woodwind", "Woodwind Ens"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind Ens/Oboe & Bassoon.T261.VCE", "Regular", "Brass & Woodwind", "Woodwind Ens"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Ballad Pan Flute.T353.SWV", "Sweet!", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Chiff Pan Flute.T353.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Celtic Duo.T260.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Ethnic Flute.T353.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Bagpipe.T262.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Ocarina.T357.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Recorder.T356.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Shakuhachi.T355.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Brass & Woodwind/Woodwind World/Whistle.T265.VCE", "Regular", "Brass & Woodwind", "Woodwind World"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Vibraphone.T263.SWV", "Sweet!", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Xylophone.T359.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Jazz Vibraphone.T263.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Marimba.T358.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Tremolo Vibraphone.T263.NLV", "Natural!", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Vibraphone.T263.NLV", "Natural!", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Vibraphone & JazzGt.T263.SAR", "S.Art!", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Glockenspiel.T362.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Vibraphone & Flutes.T263.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Steel Drums.T360.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Music Box.T363.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Chromatic Perc/Kalimba.T365.VCE", "Regular", "Perc & Drums", "Chromatic Perc"},
		{"PRESET:/VOICE/Perc & Drums/Orchestral Perc/Orchestral Harp.T338.VCE", "Regular", "Perc & Drums", "Orchestral Perc"},
		{"PRESET:/VOICE/Perc & Drums/Orchestral Perc/Tubular Bells.T364.VCE", "Regular", "Perc & Drums", "Orchestral Perc"},
		{"PRESET:/VOICE/Perc & Drums/Orchestral Perc/Mellow Harp.T338.VCE", "Regular", "Perc & Drums", "Orchestral Perc"},
		{"PRESET:/VOICE/Perc & Drums/Orchestral Perc/Timpani.T339.VCE", "Regular", "Perc & Drums", "Orchestral Perc"},
		{"PRESET:/VOICE/Perc & Drums/Orchestral Perc/Orchestra Hit.T251.VCE", "Regular", "Perc & Drums", "Orchestral Perc"},
		{"PRESET:/VOICE/Perc & Drums/Orchestral Perc/Celesta.T361.VCE", "Regular", "Perc & Drums", "Orchestral Perc"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Real Drums.T373.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Real Brushes.T375.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Power Kit 1.T267.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Power Kit 2.T267.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Acoustic Kit.T373.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/House Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Rock Kit.T267.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Drum Machine.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Studio Kit.T267.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Analog T8 Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Analog T9 Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Jazz Kit.T373.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Break Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Hit Kit.T267.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Hip Hop Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Room Kit.T373.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Dance Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Electro Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Analog Kit.T374.DRM", "Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Symphony Kit.T376.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/Drum Kits/Brush Kit.T375.LDR", "Live!Drums", "Perc & Drums", "Drum Kits"},
		{"PRESET:/VOICE/Perc & Drums/World Perc Kits/Turkish Kit.T382.LSF", "Live!SFX", "Perc & Drums", "World Perc Kits"},
		{"PRESET:/VOICE/Perc & Drums/World Perc Kits/Cuban Kit.T377.LSF", "Live!SFX", "Perc & Drums", "World Perc Kits"},
		{"PRESET:/VOICE/Perc & Drums/World Perc Kits/Pop Latin Kit.T377.LSF", "Live!SFX", "Perc & Drums", "World Perc Kits"},
		{"PRESET:/VOICE/Perc & Drums/SFX/New SFX Kit 1.T266.LSF", "Live!SFX", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/New SFX Kit 2.T266.LSF", "Live!SFX", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/Helicopter.T266.LIV", "Live!", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/Noises Kit.T266.SFX", "SFX", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/Applause 1.T266.LIV", "Live!", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/Applause 2.T266.LIV", "Live!", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/Sea Shore.T266.LIV", "Live!", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/Gun Shot.T266.LIV", "Live!", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/SFX Kit 1.T266.SFX", "SFX", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/SFX Kit 2.T266.SFX", "SFX", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Perc & Drums/SFX/Magic Bell.T270.SAR", "S.Art!", "Perc & Drums", "SFX"},
		{"PRESET:/VOICE/Synth/Synth Lead/Sub Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Wire Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Soft Saw.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Soft R&B.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Fusion Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Early Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Oxygen.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Soft Square.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Matrix.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Detuned Vintage.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/PWM Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Hipa Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Brassy Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Punchy Hook.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Punch Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Crying Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Flange Filter.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Hip Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Mouth Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Hop Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Tech Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Analogon.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Tekkline.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Skyline.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Soft Mini.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Bleep Lead.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Fire Wire.T248.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Lead/Orbit Sine.T274.VCE", "Regular", "Synth", "Synth Lead"},
		{"PRESET:/VOICE/Synth/Synth Perc/New Heaven.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Heaven Pad.T273.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Fantasy Bells.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Breath Bells.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Itopia Bells.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Next Generation.T273.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Sinesphere.T273.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Organ Bells.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Spectrum Theme.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Sky Bells.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Flying Harmonics.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Nylon Heaven.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Airy Harp.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Nylon Pad.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Simple Comp.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Bellsphere.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Ballad Comp.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Perc Pad.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Heaven Bell.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Mediterrain.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Bright Pad Bell.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Lektro Codes.T248.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Wild PWM.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Resonant Clavi.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Resonance Comp.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Perc Sequence FM 1.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Perc Sequence FM 2.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Digital Sequenced.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Synth Sticks.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Analog Sequenced.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Saz Feeze.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Perc Sequence FS.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Eastern Air.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Xtune.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Nomad.T275.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Perc Sequence Saw.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Stack Bell.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Attack.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/Nice Bell.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Perc/PWM Percussion.T270.VCE", "Regular", "Synth", "Synth Perc"},
		{"PRESET:/VOICE/Synth/Synth Strings/Synth Strings 1.T271.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Synth Strings 2.T271.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Butter Strings.T275.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Bright Saw Pad.T273.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Light Pad.T273.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Ober Strings.T271.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Hipa Strings.T275.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/80s Pad.T271.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Octave Strings.T273.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Bright Pop Pad.T273.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Medium Tune Pad.T273.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Doux Flange.T275.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Premium Pad.T273.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Bright Pad Classic.T273.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Strings/Soft Ensemble.T271.VCE", "Regular", "Synth", "Synth Strings"},
		{"PRESET:/VOICE/Synth/Synth Brass/Analog Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/1984 Synth.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Fat Synth Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/80s Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Thinth Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Funky Analog.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Brass Profit.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Techno Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Ober Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Ober Horns.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Slow PWM Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Soft Velo Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Fast PWM Brass.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Brass/Soft Analog.T272.VCE", "Regular", "Synth", "Synth Brass"},
		{"PRESET:/VOICE/Synth/Synth Pad/All or Nothing.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Whisper Gallery.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Digisweeper.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Hybrid Lines.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Spectrum Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Midnight Special.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Hybrid Pad.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Atmo 5th.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Deep Motion.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Pad Voices.T273.LIV", "Live!", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Skydiver.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Aerosphere.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Cross Phase.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/New Atmosphere.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Galaxy Pad.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/VP Soft.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Night Motion.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Hot Swell.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Morning Dew.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Dark Fat Saw.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Vapor Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Dark Light.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Space Rider.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Ambient Pad.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Pearls Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Bright Fat Saw.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Breath Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Early Digital.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Noble Man.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Super Dark Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Analog Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Analog Swell.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Dark Angel Pad.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Big Octave Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Lite Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Golden Age.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Pop Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Solaris.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Glorious Phase.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Insomnia.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Ober Sweep.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Neo Warm Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Time Travel.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Cyber Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Bubblespace.T275.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Bright Ober.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Mellow Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Pad/Dark Pad.T273.VCE", "Regular", "Synth", "Synth Pad"},
		{"PRESET:/VOICE/Synth/Synth Dance/Ana Dayz.T275.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/HPF Dance.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Bright Pad Trance.T273.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Detuned Saw Octave.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Chillin Chords.T273.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Dancy Hook.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Trance (Pedal).T273.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Vinalog Saw.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Club Lead.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Talk Mod Lead.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Trance Perc.T270.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Chorus Saw Lead.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Chordmaster.T270.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Faaat Comp.T275.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Fat Saw Hook.T272.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Tech Glide.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Trance Sequence 1.T270.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Trance Sequence 2.T270.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Trance Sequence 3.T270.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Dance Chords.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Dance Hook.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Trance Lead.T273.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Dance/Octave Hook.T274.VCE", "Regular", "Synth", "Synth Dance"},
		{"PRESET:/VOICE/Synth/Synth Effects/Water Games.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Spectralis.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/My Generation.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Metallic Rain.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Rainy Day.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Ambient Theme.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Warped Waves.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Reflecting Zone.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Sound Pictures.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/The Fog.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Mystic Pad.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Randomizer.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Atlantis.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Tric-Trac.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Sixth Sense.T275.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Perc Sequence Hipa.T270.VCE", "Regular", "Synth", "Synth Effects"},
		{"PRESET:/VOICE/Synth/Synth Effects/Pitch Fall.T270.VCE", "Regular", "Synth", "Synth Effects"},
	};

	// For whatever reason Xcode6 for iOS cannot initialize std::vector with an initializer list.
	// As a workaround we initilize static array, then use it to initialize the vector.

	VoiceList voices(voicesArr, voicesArr + sizeof(voicesArr) / sizeof(voicesArr[0]));
}

VoiceList& Presets::Voices()
{
	return voices;
}
